[package]
authors = ["Josh Leverette <coder543@gmail.com>"]
name = "rush"
version = "0.1.0"

[[bin]]
doc = false
name = "rush"

[dependencies]
pancurses = "0.11.0"
try_opt = "0.1.1"
username = "0.2.0"
[profile.dev]
codegen-units = 32

[profile.release]
lto = true
